apiVersion: openchoreo.dev/v1alpha1
kind: ComponentRelease
metadata:
  name: frontend-7b499241
spec:
  componentProfile:
    parameters:
      port: 80
      replicas: 1
  componentType:
    resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels: ${metadata.labels}
          name: ${metadata.name}
          namespace: ${metadata.namespace}
        spec:
          replicas: ${parameters.replicas}
          selector:
            matchLabels: ${metadata.podSelectors}
          template:
            metadata:
              labels: ${metadata.podSelectors}
            spec:
              containers:
              - args: |
                  ${has(workload.containers[parameters.containerName].args) ? workload.containers[parameters.containerName].args : oc_omit()}
                command: |
                  ${has(workload.containers[parameters.containerName].command) ? workload.containers[parameters.containerName].command : oc_omit()}
                envFrom: ${configurations.toContainerEnvFrom(parameters.containerName)}
                image: ${workload.containers[parameters.containerName].image}
                imagePullPolicy: ${parameters.imagePullPolicy}
                name: ${parameters.containerName}
                ports:
                - containerPort: ${parameters.port}
                  name: http
                  protocol: TCP
                resources:
                  limits:
                    cpu: ${envOverrides.resources.limits.cpu}
                    memory: ${envOverrides.resources.limits.memory}
                  requests:
                    cpu: ${envOverrides.resources.requests.cpu}
                    memory: ${envOverrides.resources.requests.memory}
                volumeMounts: ${configurations.toContainerVolumeMounts(parameters.containerName)}
              volumes: ${configurations.toVolumes()}
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          labels: ${metadata.labels}
          name: ${metadata.componentName}
          namespace: ${metadata.namespace}
        spec:
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: ${parameters.port}
          selector: ${metadata.podSelectors}
          type: ClusterIP
    - id: httproute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          labels: ${metadata.labels}
          name: ${metadata.name}
          namespace: ${metadata.namespace}
        spec:
          hostnames:
          - ${metadata.componentName}-${metadata.environmentName}.${dataplane.publicVirtualHost}
          parentRefs:
          - name: gateway-default
            namespace: openchoreo-data-plane
          rules:
          - backendRefs:
            - name: ${metadata.componentName}
              port: 80
    - forEach: ${configurations.toConfigEnvsByContainer()}
      id: env-config
      template:
        apiVersion: v1
        data: |
          ${envConfig.envs.transformMapEntry(index, env, {env.name: env.value})}
        kind: ConfigMap
        metadata:
          name: ${envConfig.resourceName}
          namespace: ${metadata.namespace}
      var: envConfig
    - forEach: ${configurations.toConfigFileList()}
      id: file-config
      template:
        apiVersion: v1
        data:
          ${config.name}: |
            ${config.value}
        kind: ConfigMap
        metadata:
          name: ${config.resourceName}
          namespace: ${metadata.namespace}
      var: config
    - forEach: ${configurations.toSecretEnvsByContainer()}
      id: secret-env-external
      template:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: ${secretEnv.resourceName}
          namespace: ${metadata.namespace}
        spec:
          data: |
            ${secretEnv.envs.map(secret, {
              "secretKey": secret.name,
              "remoteRef": {
                "key": secret.remoteRef.key,
                "property": has(secret.remoteRef.property) ? secret.remoteRef.property : oc_omit()
              }
            })}
          refreshInterval: 15s
          secretStoreRef:
            kind: ClusterSecretStore
            name: ${dataplane.secretStore}
          target:
            creationPolicy: Owner
            name: ${secretEnv.resourceName}
      var: secretEnv
    - forEach: ${configurations.toSecretFileList()}
      id: secret-file-external
      template:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: ${file.resourceName}
          namespace: ${metadata.namespace}
        spec:
          data:
          - remoteRef:
              key: ${file.remoteRef.key}
              property: |
                ${has(file.remoteRef.property) ? file.remoteRef.property : oc_omit()}
            secretKey: ${file.name}
          refreshInterval: 15s
          secretStoreRef:
            kind: ClusterSecretStore
            name: ${dataplane.secretStore}
          target:
            creationPolicy: Owner
            name: ${file.resourceName}
      var: file
    schema:
      envOverrides:
        resources: ResourceRequirements | default={}
      parameters:
        containerName: string | default=main
        imagePullPolicy: string | default=IfNotPresent
        port: integer | default=80
        replicas: integer | default=1
      types:
        ResourceQuantity:
          cpu: string | default=100m
          memory: string | default=256Mi
        ResourceRequirements:
          limits: ResourceQuantity | default={}
          requests: ResourceQuantity | default={}
    workloadType: deployment
  owner:
    componentName: frontend
    projectName: doclet
  workload:
    containers:
      main:
        files:
        - key: config.json
          mountPath: /usr/share/nginx/html
          value: |
            {
              "docServiceUrl": "http://default.development.openchoreoapis.localhost:19080/document-svc",
              "collabWsUrl": "ws://default.development.openchoreoapis.localhost:19080/collab-svc/ws"
            }
        image: host.k3d.internal:10082/doclet-frontend-image:v1-7b499241
