apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: nats
  namespace: default
spec:
  owner:
    projectName: doclet

  componentType:
    name: deployment/message-broker
    kind: ComponentType

  parameters:
    replicas: 1
    port: 4222
