apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: nats
  namespace: default
spec:
  owner:
    componentName: nats
    projectName: doclet
  container:
    image: nats:2.10-alpine
    args:
      - "--http_port"
      - "8222"
