apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend-workload
  namespace: default
spec:
  connections:
  - component: document-svc
    endpoint: http
    envBindings:
      address: DOC_SERVICE_URL
    visibility: project
  - component: collab-svc
    endpoint: http
    envBindings:
      address: COLLAB_SERVICE_URL
    visibility: project
  container:
    image: host.k3d.internal:10082/doclet-frontend-image:v1-ba0e100a
  endpoints:
    http:
      port: 80
      type: HTTP
      visibility:
      - external
  owner:
    componentName: frontend
    projectName: doclet
