apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend-workload
  namespace: default
spec:
  container:
    image: host.k3d.internal:10082/doclet-frontend-image:v1-4a2acc61
  endpoints:
    http:
      type: HTTP
      port: 80
      visibility: [external]
  connections:
    - component: document-svc
      endpoint: http
      visibility: project
      envBindings:
        address: DOC_SERVICE_URL
    - component: collab-svc
      endpoint: http
      visibility: project
      envBindings:
        address: COLLAB_SERVICE_URL
  owner:
    componentName: frontend
    projectName: doclet
