apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: standard
  annotations:
    openchoreo.dev/display-name: Standard Pipeline
    openchoreo.dev/description: Standard deployment pipeline with dev, staging, and production environments
  labels:
    openchoreo.dev/name: standard
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
